# Generated by Django 4.0.4 on 2022-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproxy",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
