# Generated by Django 4.0.4 on 2022-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_vehicleproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractProxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Active"),
                            ("2", "Inactive"),
                            ("3", "Deleted"),
                            ("4", "Blocked"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contract_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
