# Generated by Django 4.0.4 on 2022-06-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_contractproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractproxy",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.customerproxy",
            ),
        ),
    ]
