# Generated by Django 4.0.4 on 2022-07-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_contractproxy_contract_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleproxy",
            name="speed_threshold",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="vehicleproxy",
            name="vehicle_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
