# Generated by Django 4.0.4 on 2022-07-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_vehicleproxy_speed_threshold_vehicleproxy_vehicle_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpackageallocationproxy",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_package_allocation",
                to="common.customerproxy",
            ),
        ),
    ]
