# Generated by Django 4.0.4 on 2022-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_alter_customerpackageallocationproxy_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractproxy",
            name="contract_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
