# Generated by Django 4.0.4 on 2022-07-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_alter_task_drop_off_alter_task_pick_up"),
        ("common", "0009_contractproxy_contract_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContractProxy",
        ),
    ]
