# Generated by Django 3.2.13 on 2022-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_userproxy_email_otp_userproxy_mobile_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleproxy',
            name='device_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
