# Generated by Django 3.2.7 on 2022-07-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_alter_customerproxy_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleproxy",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleproxy",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleproxy",
            name="speed_threshold",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleproxy",
            name="vehicle_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
