# Generated by Django 3.2.7 on 2022-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_auto_20220728_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleproxy",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
