# Generated by Django 3.2.7 on 2022-08-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_vehicleproxy_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleproxy",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
