# Generated by Django 3.2.7 on 2022-08-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_vehicleproxy_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerFeaturesAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Active"),
                            ("2", "Inactive"),
                            ("3", "Deleted"),
                            ("4", "Blocked"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("11", "Manage Drivers"),
                            ("104", "Manage Shifts"),
                            ("105", "Manage Jobs"),
                            ("13", "Driver to Vehicle Allocation"),
                            ("37", "Driver to Shift Allocation"),
                            ("107", "Tools"),
                            ("108", "Saved Location"),
                            ("115", "Audit"),
                            ("113", "Report"),
                            ("117", "Driver App"),
                            ("2", "Overall Dashboard"),
                            ("1", "Fleet Dashboard"),
                            ("16", "Driver Dashboard"),
                            ("4", "Maintenance Dashboard"),
                        ],
                        max_length=255,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.customerproxy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
