# Generated by Django 3.2.7 on 2022-08-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_customerfeaturesassociation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelProxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Active"),
                            ("2", "Inactive"),
                            ("3", "Deleted"),
                            ("4", "Blocked"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_filled",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount_paid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fuel_supervisor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fill_up_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.customerproxy",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.vehicleproxy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
