# Generated by Django 3.2.7 on 2022-08-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_fuelproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelproxy",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuels",
                to="common.vehicleproxy",
            ),
        ),
    ]
