# Generated by Django 3.2.7 on 2022-09-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_auto_20220912_1922"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Active"),
                            ("2", "Inactive"),
                            ("3", "Deleted"),
                            ("4", "Blocked"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_token", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
