# Generated by Django 3.2.13 on 2022-10-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_auto_20220912_1922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerproxy",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
