# Generated by Django 3.2.13 on 2022-10-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_alter_customerproxy_name"),
        ("common", "0021_blacklisttoken"),
    ]

    operations = []
